# Based on:
# - https://github.com/marketplace/actions/build-and-push-docker-images
# - https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md

name: Docker Image CI

on:
  push:
    branches: [main]

# Required for secrets.GITHUB_TOKEN
permissions:
  packages: write
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo ${{ github.repository }}
