# Based on:
# - https://github.com/marketplace/actions/build-and-push-docker-images
# - https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md

name: Docker Image CI

on:
  push:
    branches: [main]

# Required for secrets.GITHUB_TOKEN
permissions:
  packages: write
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/$GITHUB_REPOSITORY:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
